### ISSUE TITLE
polyglot persistence possible with bolt_sips?

### ISSUE THREAD

**Issue by niccolox** [florinpatrascu/bolt_sips#1]
how do you feel about multi database connections? 

i.e. polyglot persistence

its possible with mysql and postgres apparently

http://geoffreylessel.com/2016/connecting-to-multiple-databases-with-ecto/

**Comment by niccolox** [comment]
?

**Comment by niccolox** [comment]
another approach
https://edmz.org/personal/2016/03/09/multiple_databases_with_ecto_and_phoenix.html

**Comment by florinpatrascu** [comment]
You can use Bolt.Sips and any other Ecto repos, in the same app - if I understand correctly, your question?!

**Comment by niccolox** [comment]
I guess I am asking for an example of how postgrex and bolt_sips would hang together

I'll leave that for now, you answered my initial question and opened up all sorts of possibilities

**Comment by florinpatrascu** [comment]
check this project: [asarode/thoughtshare](https://github.com/asarode/thoughtshare), for inspiration. See the [config/dev.exs](https://github.com/asarode/thoughtshare/blob/master/config/dev.exs), where there is a Postgresql repo and a Neo4j.Sips one. HTH

**Comment by niccolox** [comment]
thanks for this ! very cool
