### ISSUE TITLE
Config field for `timeout` not reflected in query timeouts

### ISSUE THREAD

**Issue by ThunderHeavyIndustries** [florinpatrascu/bolt_sips#100]
## Environment
* Elixir version:  1.10.4-otp-23
* Neo4j and version: 4.2.2
* Connection scheme:  bolt://localhost:7687
* Bolt.Sips version:  bolt_sips 2.0.9 
* Operating system: OSX

## Current behavior
When setup with:
```elixir
# inside config/dev.ex
config :bolt_sips, Bolt,
  url: "bolt://localhost:7687",
  basic_auth: [username: "*****", password: "****"],
  timeout: 30_000,
  pool_size: 40
```
Running a somewhat long query (which is verified to work in the Neo4j desktop client) I'm getting timeout errors:
```elixir
[error] Bolt.Sips.Protocol (#PID<0.12378.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.12385.0> timed out because it queued and checked out the connection for longer than 15000ms
```

## Expected behavior
Changing the value in the `timeout` field in the configuration fails to be reflected in queries. I've tried setting the `timeout` to lower and higher than `15_000` and I still get errors with `for longer than 15000ms` regardless of what the `timeout` is set to in the config.

Thanks for your help!

**Comment by florinpatrascu** [comment]
@ThunderHeavyIndustries - can you please use the latest published release and let us know if the problem is fixed?! Thank you

**Comment by ThunderHeavyIndustries** [comment]
Sure thing, I'll give it a go next week and get back to you.

**Comment by ThunderHeavyIndustries** [comment]
Thanks for getting back to me on this!  I'm still experiencing the same issue/seeing the same `1500 ms` response after updating to `2.0.10`. 

Maybe there's something on my end? Setup is as above. The function calls look like this:

given a `query` which is a string (again verified to work in the Neo4j Desktop client)

```elixir
  def conn() do
    Bolt.Sips.conn()
  end

  def execute(query) do
    Bolt.Sips.transaction(conn(), fn con ->
      Bolt.Sips.query!(con, query)
    end)
  end
```

I also tried passing the timeout as part of the params
```elixir
  def execute(query) do
    Bolt.Sips.transaction(conn(), fn con ->
      Bolt.Sips.query!(con, query, %{}, timeout: 60_000)
    end)
  end
```
Which doesn't change the behavior or the error message either. Thanks again for your help on this!

**Comment by florinpatrascu** [comment]
yeah I am sorry, it was my fault. It should work now with 2.0.11.

Here's one easy way to test, provided you have the [APOC](https://github.com/neo4j-contrib/neo4j-apoc-procedures/) enabled:

```elixir
{:ok, _neo} = Sips.start_link(url: "bolt://neo4j:test@localhost")
conn = Sips.conn()

Sips.query(conn, "CALL apoc.util.sleep(30000) RETURN 1 as test", %{}, timeout: 35_000)
```

HTH

**Comment by ThunderHeavyIndustries** [comment]
ah cool ok I'll test it on monday, thanks again!

**Comment by ThunderHeavyIndustries** [comment]
SO SORRY! Crazy week I'll be checking it out later today!

**Comment by florinpatrascu** [comment]
No worries, please take your time :)) many thanks

**Comment by ThunderHeavyIndustries** [comment]
Yes indeed updating does seem to respect the timeout when the query is run as presented, with one caveat! 

This still seems to be dying with the `longer than 15000ms` error message when passed as such:
```elixir
  def execute(query) do
    Bolt.Sips.transaction(conn(), fn con ->
      Bolt.Sips.query!(con, query)
    end)
  end
```
or
```elixir

  def execute(query) do
    Bolt.Sips.transaction(conn(), fn con ->
      Bolt.Sips.query!(con, query, %{}, timeout: 30_000)
    end)
  end
```
but this does respect the timeout whether set from the config, or passed in the params
```elixir
  def execute(query) do
      # :timeout set in config
      Bolt.Sips.query!(conn(), query, %{})
  end
```
or
```elixir
  def execute(query) do
    Bolt.Sips.query!(conn(), query, %{}, timeout: 30_000)
  end
```

**Comment by florinpatrascu** [comment]
Oh that's interesting, thank you for such a thorough investigation and for the examples. I'm going to look into the transaction next, in case it is related, and will report back my findings. Many thanks again!

**Comment by florinpatrascu** [comment]
I see what is going on. When you wrap your queries in transactions, Bolt.Sips delegates the call to the underlining library: **DBConnection**, including your custom  ... _options_ ;)

Please try this instead:

```elixir
  def execute(query) do
    Bolt.Sips.transaction(conn(), fn con ->
      Bolt.Sips.query!(con, query)
    end, timeout: 30_000)
  end
```

**Comment by ThunderHeavyIndustries** [comment]
I'll give that a go tomorrow!

**Comment by florinpatrascu** [comment]
please reopen, in case you find any other related issue. Thanks again!
