### ISSUE TITLE
Going forward 

### ISSUE THREAD

**Issue by kristofka** [florinpatrascu/bolt_sips#112]
Hi,
I’m almost ready to make a new revision of bolt_sips with support for bolt 4+, however I feel we should split the project: at the very least it would be nice to have a mint like functional client,
then bolt_sips could depend on that. Ideally I’d also like to split packstream encoder/decoder into its own lib. 
I went ahead and created a neo4ex org on GitHub to hold various libs related to bolt and elixir (I’ve invited you and @dominique-vassard ), the goal would be to provide 
- a mint like functional client;
- a Dbconnection wrapper (current bolt_sips)
- Ideally an independent packstream encoder/decoder
- Ideally an ecto like dsl
Hope you’re ok with that project.

**Comment by florinpatrascu** [comment]
That's very good thinking. I'll update this project with a corresponding link, to inform visitors about the your new project that will host the development for neo4j and Elixir, moving forward. Thank you.

**Comment by hickscorp** [comment]
Hi there @kristofka and @florinpatrascu,

We're discovering that `bolt_sips` seems to not be maintained anymore, and saw this issue from last year. Did you end up publishing `neo4ex` publicly / get something to work with Bolt 3/4/5?

We might decide to add more recent versions of Bolt as an opensource contribution... But could benefit from hints / pointers if you've already put some effort in it.

Thanks!

**Comment by florinpatrascu** [comment]
Hi @hickscorp - I can update the readme and include a link to your repository, provided that you have a more recent version or fork.

**Comment by hickscorp** [comment]
Good morning @florinpatrascu , and thanks for taking the time.

In the end, we found a package named boltx and it seems to cover what we need.

**Comment by florinpatrascu** [comment]
np
> In the end, we found a package named boltx and it seems to cover what we need.

Yes that's the only more advanced fork I know about so far, and the link was already in the readme. I am really happy it works for you, good luck!
