### ISSUE TITLE
Project's own config for bolt.cypher task

### ISSUE THREAD

**Issue by subversive-owl** [florinpatrascu/bolt_sips#20]
This was mentioned on [line 32](https://github.com/florinpatrascu/bolt_sips/blob/master/lib/mix/tasks/cypher.ex#L32) of the task definition.

I personally would like to use this as a starting point for writing other tasks for Bolt, like setting up constraints, so I'm interested in this too, but I have no Elixir skill yet.

**Comment by florinpatrascu** [comment]
I'll start working on that, shouldn't be any troubles with it.

**Comment by florinpatrascu** [comment]
Package published to https://hex.pm/packages/bolt_sips/0.3.2

Please see the updated README, for details. HTH - Florin
