### ISSUE TITLE
hex package contains an erl_crash.dump file

### ISSUE THREAD

**Issue by mkrogemann** [florinpatrascu/bolt_sips#26]
More of a stylistic thing but most likely not intended.

When I install the current (0.2.5) package and look at its content, I find an erl_crash.dump file in lib.

Big Kudos and Many Thanks for providing this package by the way 👍

**Comment by florinpatrascu** [comment]
Arghhh, my bad, sorry!!! I'll clean it up as soon as I get back to a computer, 1-2 hours, and will publish the cleaner version. Thanks for catching it, and for the kind words!

**Comment by florinpatrascu** [comment]
done :) Package published to https://hex.pm/packages/bolt_sips/0.2.6, thanks again!

**Comment by mkrogemann** [comment]
I still find the crash dump in the tarball of 0.2.6. I hope that my local hex folder is not corrupted and I am not reporting this wrongly.

**Comment by florinpatrascu** [comment]
Probably my fault, I'll clean it up this weekend, as I also have some more code cleanup done, ready to be committed and a few packages updated too; not a big release, but a new one nevertheless:) Thank you!

**Comment by florinpatrascu** [comment]
Package published to https://hex.pm/packages/bolt_sips/0.3.1
