### ISSUE TITLE
"Unsupported authentication token, missing key `scheme`"

### ISSUE THREAD

**Issue by rawhat** [florinpatrascu/bolt_sips#29]
Hi,

I am trying to get the driver working in `iex` but unfortunately am running into the titular error.  It works just fine from the terminal, but I am getting these unexpected return values elsewhere.

<img width="788" alt="screen shot 2017-06-02 at 12 37 02 am" src="https://cloud.githubusercontent.com/assets/2095509/26711063/ef74f806-472b-11e7-8943-b44c378e1f34.png">

I am having the `iex` issue on both Mac and Windows.  However, none of it works on Windows, whereas the terminal command on OS X does work.

The link to my project is [here](https://github.com/rawhat/playlistr_music) if you want to look at it.

I apologize if this is not the proper forum, but I cannot find any reference to this issue anywhere else.  I also have checked my configuration against multiple examples, and everything seems fine to me.  I'm fairly stumped.  Any help would be appreciated.

Thanks!

**Comment by rawhat** [comment]
I must have had the configuration entered incorrectly, as now I believe it is working.  I'll close this now!

**Comment by florinpatrascu** [comment]
Glad you figured it out! 🍻

**Comment by agm1984** [comment]
I just ran into this error and it was because I just converted my neo4j credentials from hardcoded to dynamic based on environment config, and I had a typo on the password field.

If anyone encounters this, do a quick check like:

``` javascript
console.log('CONFIG')
console.log(host)
console.log(user)
console.log(pwd)
````

It's just a credential mismatch somewhere.
