### ISSUE TITLE
Misleading error returned, when it shouldn't: `socket is not connected`

### ISSUE THREAD

**Issue by florinpatrascu** [florinpatrascu/bolt_sips#33]
please see: issue #32, for background info.

**Comment by florinpatrascu** [comment]
fixed with v0.3.5

**Comment by cheerfulstoic** [comment]
The latest version of `bolt_sips` that I see is 0.3.5 on [the hex.pm page](https://hex.pm/packages/bolt_sips).  Is something wrong with the release process?

**Comment by florinpatrascu** [comment]
yes sorry, my fault. Published now, thank you for catching it 👍
