### ISSUE TITLE
Phoenix 1.3 Unable to start

### ISSUE THREAD

**Issue by willoughby** [florinpatrascu/bolt_sips#34]
I've followed the install guide, but get the following error.

exited in: :gen_server.call(:bolt_sips_pool, {:checkout, #Reference<0.120961608.535560200.138616>, true}, :infinity) ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
nofile

**Comment by willoughby** [comment]
I was able to resolve my issue. New to the ecosystem but had to add the following to my Application:

`worker(Bolt.Sips, [
        Application.get_env(:bolt_sips, Bolt)])`

**Comment by florinpatrascu** [comment]
That’s the correct solution! :)

**Comment by florinpatrascu** [comment]
the latest version 0.4.11, has its README updated with an example clarifying this aspect. Thank you @willoughby, for suggesting it!

**Comment by gamebox** [comment]
I am still seeing a similar issue.  Running Phoenix 1.3.4 with OTP 20 and Elixir 1.7.  Starting a new phoenix project(no brunch, no ecto) adding only the things needed per the README, and I get this:

```
** (Mix) Could not start application phx_issues: PhxIssues.Application.start(:normal, []) returned an error: shutdown: failed to start child: PhxIssuesWeb.Endpoint
    ** (EXIT) shutdown: failed to start child: Phoenix.Endpoint.Handler
        ** (EXIT) shutdown: failed to start child: {:ranch_listener_sup, PhxIssuesWeb.Endpoint.HTTP}
            ** (EXIT) exited in: :gen_server.call(:ranch_server, {:set_new_listener_opts, PhxIssuesWeb.Endpoint.HTTP, 16384, [env: [dispatch: [{:_, [], [{["phoenix", "live_reload", "socket", "longpoll"], [], Plug.Adapters.Cowboy.Handler, {Phoenix.Transports.LongPoll, {PhxIssuesWeb.Endpoint, Phoenix.LiveReloader.Socket, :longpoll}}}, {["phoenix", "live_reload", "socket", "websocket"], [], Phoenix.Endpoint.CowboyWebSocket, {Phoenix.Transports.WebSocket, {PhxIssuesWeb.Endpoint, Phoenix.LiveReloader.Socket, :websocket}}}, {["socket", "websocket"], [], Phoenix.Endpoint.CowboyWebSocket, {Phoenix.Transports.WebSocket, {PhxIssuesWeb.Endpoint, PhxIssuesWeb.UserSocket, :websocket}}}, {:_, [], Plug.Adapters.Cowboy.Handler, {PhxIssuesWeb.Endpoint, []}}]}]], onresponse: #Function<1.129103586/4 in Plug.Adapters.Cowboy.add_on_response/3>]})
                ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
```
I have a more mature app that I've added bolt_sips to receive a similar, but not identical error.
