### ISSUE TITLE
Proposal: use git tags for releases.

### ISSUE THREAD

**Issue by MachinesAreUs** [florinpatrascu/bolt_sips#40]
this would ease tracking diagnostics against previous versions.

**Comment by florinpatrascu** [comment]
Of course, but how is this different than what I am currently doing?!

**Comment by MachinesAreUs** [comment]
It would allow navigation to a specific version from the repository main page :)

**Comment by florinpatrascu** [comment]
sure thing, I'll make sure I'll continue to tag the every noticeable release, from now on. Right now there is only one tag :) Thank you for the suggestion!

**Comment by florinpatrascu** [comment]
[v0.5.7](https://github.com/florinpatrascu/bolt_sips/tree/v0.5.7) created :)

**Comment by MachinesAreUs** [comment]
Great! Is there a reason this version is not on [hex.pm](https://hex.pm/packages/bolt_sips)?

**Comment by florinpatrascu** [comment]
@MachinesAreUs, yes there is one, and I am getting this question a lot lately :) We depend on the db-connection, its master version. Details here: #39, HTH
