### ISSUE TITLE
date & datetime support

### ISSUE THREAD

**Issue by namxam** [florinpatrascu/bolt_sips#44]
Is there a way to get date and datetime properties working with `0.4.12`?

I am currently getting `Neo.ClientError.Request.Invalid` with `DateTime is not yet supported as a return type in Bolt`.

**Comment by florinpatrascu** [comment]
not right now, sorry. I believe this will be added to [boltex](https://github.com/mschae/boltex), tho' I can't say when. @mschae, is the best person to tell us :)

I'll make sure it is integrated in the 0.4 when it will be available, as most of the development these days is happening for the v 0.5 (routing support, and newer db_connection)

**Comment by namxam** [comment]
Ah nice. I am quite new to it and experimenting a bit with data structures and queries. I guess I will create an issue there.

**Comment by florinpatrascu** [comment]
sure thing, ty! And please mention this issue too, so I get the notifications and keep the thread coherent. Thank you!

**Comment by florinpatrascu** [comment]
https://hex.pm/packages/bolt_sips/1.0.0-rc2, is on Hex.pm paving the road for future development.

**Comment by dominique-vassard** [comment]
Neo4j date types come with timezone, which are supported in elixir 1.8 without the need of an external dependency (calendar to name it).
Do you consider using elixir 1.8 a viable option to add temporal type support?

**Comment by florinpatrascu** [comment]
As far as I am concerned, I am good with using Elixir's features as out of the box as possible - it's new releases are very stable, from my personal experience -  but I am not sure how will other users receive this suggestion?!

**Comment by florinpatrascu** [comment]
@namxam - please check the newest version (in master). @dominique-vassard - added lots of good stuff lately, including: [using-temporal-and-spatial-types](https://github.com/florinpatrascu/bolt_sips#using-temporal-and-spatial-types) Please let us know how it works for you.

**Comment by florinpatrascu** [comment]
available at Hex: https://hex.pm/packages/bolt_sips/1.2.0-rc2

**Comment by florinpatrascu** [comment]
@namxam & @dominique-vassard - can we close this?

**Comment by dominique-vassard** [comment]
ok for me
