### ISSUE TITLE
Runtime configuration

### ISSUE THREAD

**Issue by namxam** [florinpatrascu/bolt_sips#45]
The docs only explain configuration via classic elixir config mechanism. We are using releases and try to configure all services during runtime via environment variables. What would be the suggested way to achieve it with bolt_sips? Creating my own worker / supervisor which loads config with init/1? Or is there a way to hook into bolt_sips' init/1 callback?

**Comment by florinpatrascu** [comment]
Indeed, I should probably start updating the README more often, you're right. Meanwhile, you could try the following approach. Say your `config/prod.exs` contains a Distillery-compliant var that would be defined at runtime, for example:

```elixir
config :bolt_sips, Bolt,
  url: "${NEO4J_URL}",
  ssl: "${IS_SSL}" # and so on
```
then you could have something like this:

```elixir
defmodule MyApp do
  use Application

  def start(_type, _args) do
    import Supervisor.Spec

    children = [
      # Start the endpoint when the application starts
      worker(Bolt.Sips, [Application.get_env(:bolt_sips, Bolt)]),
      # ...
    ]

    opts = [strategy: :one_for_one, name: MyApp.Supervisor]
    Supervisor.start_link(children, opts)
  end

end
```
And yes, the next version will have a callback, same as Ecto :)

Let me know if this works for you?!

HTH

**Comment by namxam** [comment]
Thank you. I guess that is the easiest way for now.

But good to know, that you think about adding something similar to what Ecto and Phoenix implement. I guess it is fantastic if there is a _common way_ to handle runtime configuration.

**Comment by florinpatrascu** [comment]
>  I guess it is fantastic if there is a common way to handle runtime configuration

I wish it was that simple, but the future of configruations is not yet settled. Check the latest discussions about the config, in the Elixir community ;)

But regardless, we have solutions right now, and they work well, until the role that Mix will play in the prod config will be defined. My advice: stick to Distillery, and releases, because it is done well.
