### ISSUE TITLE
Documentation: public / private / guides?

### ISSUE THREAD

**Issue by dominique-vassard** [florinpatrascu/bolt_sips#62]
Hi,
As project grows, document does too.
I found current Hex documentation a little bit messy and it doesn't help user to leverage the true power of bolt_sips.

What can we do?
 - Expose public API in a clear way. As an example today, `Bolt.Sips.ConfigAgent` is at the same level as `Bolt.Sips.Types`, and we know that the first is for internal use only.
We could benefit of the grouping capability of ExDoc to have a clear separation between public API and internal doc (because it's nice to not have to look into the code for some docs...)
- Keep the README.md for github and have some nice "Guide" section on Hex with visible TOC and all 

What do you think,

**Comment by florinpatrascu** [comment]
Hi Dominique - the documentation is indeed lacking and we'll have to clean it up. It's mostly my fault for just documenting the code I was writing, thinking the driver will not become more than a simple toy a user could use for learning Neo4j & Elixir :) As time passed it became more complex and its applicability today goes beyond a simple ... mix task ... one could use for playing with Neo4j and learn Cypher. 

To address your points:

-  `Bolt.Sips.ConfigAgent` was a quick hack I used for replacing the cache I used to have before. Moving forward the need for a better config store may be more important and we'll have to refactor this - but yes, it shouldn't be public. Plus it will get trickier if we want to integrate the `bolt+routing` protocol.
- I'd say the README should be become just a quick "usage guide", to help newcomers hit the road and be able to start poking at Neo4j as soon as possible, but we should evolve the docs into a small driver manual of some sort, with plenty of examples?! Maybe the community will help too? :)

For the documentation, I was already contemplating a different medium i.e. [GatsbyJS](https://www.gatsbyjs.org)? This is a similar approach Distillery took when they realized the "Readme" can't just be the official docs, anymore.

Probably the easier path from all of the above would be just to use ExDoc's abilities better, as a start?!

**Comment by dominique-vassard** [comment]
I do like docs with example and explicitness everywhere, that usually makes me want to use the thing and believe the thing is great. 
And as bolt sips is different from other Neo4j driver, an extensive doc is mandatory event for Neo4j "senior" users.
I don't think we anything but Hex for doc for now but why not an external site if it's not a considerable amount of work. The distillery example is a good one: as I saw, it's just simple Markdown as we should do for Hex, so no extra work needed :)

**Comment by dominique-vassard** [comment]
GatsbyJS looks a bit overpowered for our needs. It's highly customizable yes but I'm more into simpler alternatives, which are still very efficient like [mkdocs](https://www.mkdocs.org) or [docsify](https://docsify.js.org).

**Comment by florinpatrascu** [comment]
I honestly looked at it first because I like shiny things :) I am sucker for good fonts, clear layouts and  natural color palettes; spending lot of time customizing my Terminal, editors and so on. But the most important aspects I was looking at when reading about GatsbyJS, were: publishing and the ability to write markdown. Both being very well supported, by GatsbyJS.

Publishing is so easy too. One click and the github repo containing the docs can be up in seconds, on Netlify (and similar)

However, I didn't spend much time on reading too much from its docs, which is a shame, there are only so many weekends in a year :( Therefore I might've overlook some aspects that could bite us later .. I don't know 🤷‍♂️

**Comment by florinpatrascu** [comment]
few thoughts - working at the routing part these days, I realized how much we need to work for bringing the documentation where we want it to be. And the new functionality will only add more docs to the exiting ones. Let's stay with the support we have in the language itself; module docs, doctests, readmes and eventually a folder with examples and their associated go-through mini-guides. At least the users will be able to use hexdocs for finding the answers they need, w/o needing to go to a different server for them. Later, when the new driver will be released, and if any kind souls would like to help us with creating a better support for documentation, then we can focus on that at that time :)

**Comment by florinpatrascu** [comment]
the documentation will be hosted by HexDocs
