### ISSUE TITLE
Application exited: shutdown

### ISSUE THREAD

**Issue by yoelfme** [florinpatrascu/bolt_sips#74]
## Environment

* Elixir version (elixir -v): 1.8.0
* Neo4j and version (Neo4j 3.5.3, etc.): Neo4j 3.3
* Connection scheme (`bolt://`, `bolt+routing://` or `neo4j://`): bolt://
* Bolt.Sips version (mix deps): ~> 2.0.0-rc
* Operating system: Ubuntu 18.04

## Current behavior

I just followed your [Getting started](https://github.com/florinpatrascu/bolt_sips/blob/master/docs/getting-started.md) guide, but when I try to do: `DEBUG=1 iex -S mix` I just got:
```
[info]  Application n4d exited: shutdown
```

My files are:

mix.exs
```elixir
defp deps do
  [
    {:bolt_sips, "~> 2.0.0-rc"},
    {:jason, "~> 1.1"}
  ]
end
```

application.ex
```elixir
def start(_type, _args) do
  # List all child processes to be supervised
  children = [
    # Starts a worker by calling: N4D.Worker.start_link(arg)
    # {N4D.Worker, arg}
    {Bolt.Sips, Application.get_env(:bolt_sips, Bolt)}
  ]

  # See https://hexdocs.pm/elixir/Supervisor.html
  # for other strategies and supported options
  opts = [strategy: :one_for_one, name: N4D.Supervisor]
  Supervisor.start_link(children, opts)
end
```

config.exs
```elixir
config :bolt_sips, Bolt,
  url: "bolt://localhost:7687",
  pool_size: 10
```
I don't know, what I'm doing wrong, can someone help me, thanks!

**Comment by dominique-vassard** [comment]
Hi,
What is your OTP version?
Bolt Sips uses features available in OTP 21+ and the error you encountered resembles one I faced with my own package until I upgrade OTP to version 21 :)

**Comment by yoelfme** [comment]
thanks @dominique-vassard, I'll try with that, I'm seeing that my OTP version is 20.

**Comment by florinpatrascu** [comment]
@yoelfme - any feedback on this?

**Comment by yoelfme** [comment]
sorry @florinpatrascu, it worked with the changes that @dominique-vassard said, thanks!
