### ISSUE TITLE
Consistent bad connection state after malformed query: "... You need to\n`ACK_FAILURE` or `RESET` ..."

### ISSUE THREAD

**Issue by Tomboyo** [florinpatrascu/bolt_sips#78]
I have the following fulltext index on my database:
```
CALL db.index.fulltext.createNodeIndex(
  "topic_label",
  ["topic"],
  ["label"],
  { analyzer: "simple" });
```

And the following Bolt.Sips configuration (note the pool_size of just 1):
```
[
  url: "bolt://localhost:7687",
  ssl: true,
  basic_auth: [
    username: "neo4j",
    password: "[REDACTED]"
  ],
  pool_size: 1
]
```

If I issue the following malformed query (because `badparen)` is not quoted and is therefore treated like a Lucene query containing syntax errors):
```
Bolt.Sips.query(
  Bolt.Sips.conn(),
  "CALL db.index.fulltext.queryNodes(\"topic_label\", \"badparen)\") YIELD node RETURN node")
```

Then that query correctly fails with an error from Apache Lucene:
```
{:error,
 [
   code: nil,
   message: "run_statement: Unknown failure: {:failure, %Bolt.Sips.Internals.Error{code: \"Neo.ClientError.Procedure.ProcedureCallFailed\", connection_id: 48, function: :pull_all, message: \"Failed to invoke procedure `db.index.fulltext.queryNodes`: Caused by: org.apache.lucene.queryparser.classic.ParseException: Encountered \\\" \\\")\\\" \\\") \\\"\\\" at line 1, column 8.\\nWas expecting one of:\\n    <EOF> \\n    <AND> ...\\n    <OR> ...\\n    <NOT> ...\\n    \\\"+\\\" ...\\n    \\\"-\\\" ...\\n    <BAREOPER> ...\\n    \\\"(\\\" ...\\n    \\\"*\\\" ...\\n    \\\"^\\\" ...\\n    <QUOTED> ...\\n    <TERM> ...\\n    <FUZZY_SLOP> ...\\n    <PREFIXTERM> ...\\n    <WILDTERM> ...\\n    <REGEXPTERM> ...\\n    \\\"[\\\" ...\\n    \\\"{\\\" ...\\n    <NUMBER> ...\\n    \", type: :cypher_error}}\n"
 ]}

```

But! If I then try to issue any further queries:
```
Bolt.Sips.query(Bolt.Sips.conn(), "Match (n) return n") 
```

Then they fail with the following exception:
```
{:error,
 [
   code: nil,
   message: "The session is in a failed state and ignores further messages. You need to\n`ACK_FAILURE` or `RESET` in order to send new messages.\n"
 ]}
```

I wasn't sure if this was a bug or if I was missing a configuration, but it looked like the failed state error was leaking out of internals; was something supposed to ACK or RESET on my behalf? The connection seems to stay in this bad state indefinitely, which could poison a pool over time if a running system has the right bugs in it.

Thanks!

## Environment

* Elixir version (elixir -v):
  Erlang/OTP 21 [erts-10.3.5.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
  Elixir 1.9.0 (compiled with Erlang/OTP 21)
* Neo4j and version (Neo4j 3.5.3, etc.):
  Neo4j 3.5.12
* Connection scheme (`bolt://`, `bolt+routing://` or `neo4j://`):
  bolt://
* Bolt.Sips version (mix deps):
  1.5.1
* Operating system:
  Fedora 30 (Workstation Edition)

**Comment by florinpatrascu** [comment]
thank you for the detailed report, I'll try to reproduce it on my local. This is using one of the APOC's stored procedures, right?

**Comment by Tomboyo** [comment]
To my understanding, the `db.index.fulltext.createNodeIndex` & `queryNodes` procedures come standard with 3.5. I haven't intentionally installed APOC, at least, and `CALL apoc.help('apoc')` fails due to unknown procedure.

**Comment by florinpatrascu** [comment]
@Tomboyo - would you mind testing with the code from our `master` branch and report back your findings?! Thank you!

**Comment by Tomboyo** [comment]
Gladly! I'll give it a shot this evening. :)

**Comment by Tomboyo** [comment]
I can confirm that this is working on master against my database. :)

**Comment by florinpatrascu** [comment]
I just published a new release, published to https://hex.pm/packages/bolt_sips/2.0.3, containing all the new improvements, including the fix for this issue. Please feel free to close it, if you're satisfied with the new version :)

Thank you, @Tomboyo and @kristofka!

**Comment by Tomboyo** [comment]
Just got around to building with the new release. Looks good there as well, going ahead and closing this. Thanks everyone!
