### ISSUE TITLE
Error Connecting to Remote DB

### ISSUE THREAD

**Issue by LawJolla** [florinpatrascu/bolt_sips#8]
Thank you for all of your hard work!  I'm a huge fan of Neo4J, and it's because of this project that I can use Elixir.

However, being new to Elixir, I'm not sure what I'm doing wrong or how to read this stack trace.  I'm trying to connect to GrapheneDB and get the following error:

```
iex(1)> Bolt.Sips.conn
** (exit) exited in: :gen_server.call(#PID<0.427.0>, :connect)
    ** (EXIT) an exception was raised:
        ** (FunctionClauseError) no function clause matching in Boltex.Utils."-hex_encode/1-lc$^0/1-0-"/1
            (bolt_sips) lib/boltex/utils.ex:9: Boltex.Utils."-hex_encode/1-lc$^0/1-0-"({:error, :closed})
            (bolt_sips) lib/boltex/bolt.ex:44: Boltex.Bolt.handshake/2
            (bolt_sips) lib/bolt_sips/connection.ex:41: Bolt.Sips.Connection.handle_call/3
            (stdlib) gen_server.erl:615: :gen_server.try_handle_call/4
            (stdlib) gen_server.erl:647: :gen_server.handle_msg/5
            (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
     (stdlib) gen_server.erl:204: :gen_server.call/2
    (poolboy) src/poolboy.erl:76: :poolboy.transaction/3
iex(1)> [error] GenServer #PID<0.427.0> terminating
** (FunctionClauseError) no function clause matching in Boltex.Utils."-hex_encode/1-lc$^0/1-0-"/1
    (bolt_sips) lib/boltex/utils.ex:9: Boltex.Utils."-hex_encode/1-lc$^0/1-0-"({:error, :closed})
    (bolt_sips) lib/boltex/bolt.ex:44: Boltex.Bolt.handshake/2
    (bolt_sips) lib/bolt_sips/connection.ex:41: Bolt.Sips.Connection.handle_call/3
    (stdlib) gen_server.erl:615: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:647: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: :connect
State: [timeout: 15000, hostname: "bolt://hobby.dbs.graphenedb.com", basic_auth: [username: "fakeusername", password: "fakepassword"], port: 24786, pool_size: 5, max_overflow: 1]
```

My config:

```
config :bolt_sips, Bolt,
 hostname: "bolt://hobby.dbs.graphenedb.com",
 basic_auth: [username: "fakeusername", password: "fakepassword"],
 port: 24786,
 pool_size: 5,
 max_overflow: 1
```

Any ideas?

**Comment by ivanpetrovic** [comment]
Hi,

I think you don't need to specify the protocol bolt:// in the hostname.
Just use hostname: "hobby.dbs.graphenedb.com",

**Comment by LawJolla** [comment]
Thanks for the reply!  Without the protocol, it still gives the same error.  

I'm able to connect to my localhost Neo4J instance.

**Comment by florinpatrascu** [comment]
Thank you for your kind words. Indeed, you shouldn't specify the bolt protocol in the host name, as the Bolt.Sips driver presumes Bolt and works only with the Bolt protocol. Can you specify the remote host by its IP address? Or maybe the bolt protocol on that host is not the standard one? I'll will look tonight at this, as I am not familiar with the provider you're using. Thank you both for the feedback.

**Comment by LawJolla** [comment]
Thanks for the quick response!

I don't think there's anything non-standard about the protocol.  Graphene is one of the largest certified Neo providers along with Graph Story.  I'd be surprised if they weren't supporting it correctly.

I will see if I can specify the host by remote IP.  They don't show that in their configs.

To violate every GitHub no no, but for the sake of fast trouble shooting, here is my actual config.  There's nothing of importance on my hobby db so feel free to connect and have at it.

```
config :bolt_sips, Bolt,
 hostname: "hobby-anhjkmpgjildgbkeambcakol.dbs.graphenedb.com",
 basic_auth: [username: "", password: ""],
 port: 24786,
 pool_size: 5,
 max_overflow: 1
```

It does work with the Neo4j corporate Node driver...

```
//npm install neo4-driver

const neo4j = require('neo4j-driver').v1;
const driver = neo4j.driver("bolt://hobby-anhjkmpgjildgbkeambcakol.dbs.graphenedb.com:24786", neo4j.auth.basic("", ""));
const session = driver.session();
session.run("MATCH (a:Make) return a")
.then(result => console.log(result.records[0].get('a').properties.name)) // Acura
.then(() => session.close())
.catch(err => console.log(err));
```

# UPDATE

Same error with the IP

**Comment by florinpatrascu** [comment]
Sorry to disappoint, @lawjolla, but I don't have a quick solution for this issue. 

graphene.db is encrypting the communication and Bolt.Sips is not yet provisioned for that; I'm using :gen_tcp, for socket connections. The error you saw is basically due to graphene terminating the unencrypted connection, and they're doing the right thing. 

I will start working on this, but can't say categorically when I'll have a working solution :(

**Comment by LawJolla** [comment]
Awesome!  Thanks for looking into it and the explanation.  I'll remove my credentials in the interim. :)

**Comment by florinpatrascu** [comment]
Hey @LawJolla  - I believe I have a good Bolt.Sips candidate for you, to try out with your remote Neo4j  server at graphenedb, after you finish the eggnog :) Please use the [with_tls](https://github.com/florinpatrascu/bolt_sips/tree/with_tls) branch; configuration details in the [CHANGELOG](https://github.com/florinpatrascu/bolt_sips/blob/with_tls/CHANGELOG.md)

I still have to fix the Travis CI now, for the new config, in a couple of days tho' :)

Merry Christmas, to you all!
Florin

**Comment by sntran** [comment]
Thank you so much! I was deploying my app with Graphene today and encountered the same issue. So glad that you have just made the update just at the right time.

I do have a few feedbacks:

- Because `hostname` option takes a full URI now, maybe we would want to use `url` option instead, to be the same as `neo4j-sips` and Ecto?
- Similarly, maybe `ssl` can be used instead of `secure`, so the  same option can be used with Ecto?
- There are quite a few dependencies for `etls` such as `cmake`, `ninja-build`, ... I can't really compile it under Mac OSX (El Capitan), and I'm not sure if Heroku (my staging environment) will have those dependencies either.  I'm just a specific use case here, but it may be something to consider.

**Comment by florinpatrascu** [comment]
Thank you for the feedback, @sntran.

I changed the `:secure` option name to: `:ssl`, as you suggested. There's a new commit available. 

Changing the hostname to `url` will require a bit of work, as I intend to support the both of them. When `:url` will be provided, I'll parse the string and will look for the port value too. But I am not sure I can do this today, sorry. Definitely in the next days :)

For `:etls`, try first installing ninja and gcc, that's how I compile it on OSX - my dev environment. i.e. `brew install gcc` and `are install ninja`. Should work.

Now if I could make Tracis compile too :( 

(If any TravisCI experts available, I'd need a bit of help with this. Thank you in advance!)

**Comment by LawJolla** [comment]
It works!!  Really impressive job.  I wish I had a clue how to replicate such magic. 👍 

I also had a compile struggle, but eventually overcame.  (Needed brew install cmake)

Thank you for your hard work!

**Comment by florinpatrascu** [comment]
@lawjolla - thank you so much for your very kind words. I wish it was real magic, but it's just the ability to maintain a functional balance while seating on the shoulders of giants :) My work relies on other open source projects, and I'd be a lot less efficient w/o them. Many thanks again!!

I'll close this issue as soon as I can tame Travis and make it pass, and immediately after I'll publish the code to Hex.pm HTH

**Comment by florinpatrascu** [comment]
New version (0.1.4) available at [Hex.pm](https://hex.pm/packages/bolt_sips/0.1.4). Next, will add support for getting the connection details from a `url`, if provided. Thank you all for your feedback and support!

**Comment by albertoperdomo** [comment]
I'm one of the founders at GrapheneDB.

I just became aware of this issue thread and wanted to thank @florinpatrascu and everyone else involved in this, for improving the driver and making it work with TLS & GrapheneDB. 👏 .

**Comment by florinpatrascu** [comment]
@albertoperdomo - thank you so much for your kind words. GrapheneDB being a very valuable resource for us, I am very happy the Elixir users can now use it with Bolt and in a secure mode. And thank you for the free tier too, that helped a lot with the tests and while debugging!

**Comment by florinpatrascu** [comment]
New version (0.1.5) available at [Hex.pm](https://hex.pm/packages/bolt_sips), **with** support for getting the connection details from the `url` parameter, if provided in the configuration files. 

When using a hosted Neo4j instance, for example at: [GrapheneDB.com](http://www.graphenedb.com), you only need to paste the db connection details into the `url` parameter, for example:

```elixir
config :bolt_sips, Bolt,
  url: "bolt://demo:demo@hobby-happyHoHoHo.dbs.graphenedb.com:24786",
  ssl: true
```

Happy New Year!

**Comment by eibarcenas** [comment]
Hi! I connect to my database in neo4j.com, can you help me so that the error does not occur? please

![error](https://user-images.githubusercontent.com/42219451/164550988-aed20f01-d541-4dc9-a2bd-82fd80480961.jpeg)

**Comment by eibarcenas** [comment]
"Port {:sslsocket, {:gen_tcp, #Port<0.47>, :tls_connection, :undefined}, [#PID<0.755.0>, #PID<0.754.0>]} is closed"

I get this error when connecting to neo4j.com (aura)?
Could you help me? please

**Comment by florinpatrascu** [comment]
hi please create a new issue and help us understanding more about your issue. include relevant connection details etc. Also please do not add a new report to an already closed issue that may or may not be related to yours. Thank you.

**Comment by eibarcenas** [comment]
I do exactly what is said.
I connect to a database called aura from neo4j.com

After some time of inactivity I get an error.

```
[error] Bolt.Sips.Protocol (#PID<0.572.0>) disconnected: ** (Bolt.Sips.Internals.Error) Port {:sslsocket, {:gen_tcp, #Port<0.30>, :tls_connection, :undefined}, [#PID<0.836.0>, #PID<0.801.0>]} is closed
[error] GenServer #PID<0.572.0> terminating
** (MatchError) no match of right hand side value: %Bolt.Sips.Internals.Error{code: nil, connection_id: nil, function: :goodbye, message: "goodbye: Unknown failure: \"Can't close port\"\n", type: :protocol_error}
    (bolt_sips 2.0.11) lib/bolt_sips/protocol.ex:85: Bolt.Sips.Protocol.disconnect/2
    (db_connection 2.4.2) lib/db_connection/connection.ex:164: DBConnection.Connection.disconnect/2
    (connection 1.1.0) lib/connection.ex:767: Connection.disconnect/3
    (stdlib 3.17) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.17) gen_server.erl:771: :gen_server.handle_msg/6
    (stdlib 3.17) proc_lib.erl:236: :proc_lib.wake_up/3
Last message: {:"$gen_cast", {:disconnect, #Reference<0.2559154615.1763049476.70596>, %Bolt.Sips.Internals.Error{code: nil, connection_id: nil, function: :receive_data, message: "Port {:sslsocket, {:gen_tcp, #Port<0.30>, :tls_connection, :undefined}, [#PID<0.836.0>, #PID<0.801.0>]} is closed", type: :connection_error}, %Bolt.Sips.Protocol.ConnData{bolt_version: 3, configuration: [socket: :ssl, pool_index: 38, name: {:via, Registry, {:bolt_sips_registry, "default_read@e334e499.databases.neo4j.io:7687"}}, role: :read, path: "", with_etls: false, schema: "bolt", prefix: :default, hostname: 'e334e499.databases.neo4j.io', basic_auth: [username: "neo4j", password: ""], port: 7687, pool_size: 50, ssl: true, max_overflow: 5, timeout: 15000, server_version: %{"connection_id" => "bolt-6752", "hints" => %{"connection.recv_timeout_seconds" => 60}, "server" => "Neo4j/4.4-aura"}], sock: {:sslsocket, {:gen_tcp, #Port<0.30>, :tls_connection, :undefined}, [#PID<0.836.0>, #PID<0.801.0>]}}}}
State: {Bolt.Sips.Protocol, %Bolt.Sips.Protocol.ConnData{bolt_version: 3, configuration: [socket: :ssl, pool_index: 38, name: {:via, Registry, {:bolt_sips_registry, "default_read@.neo4j.io:7687"}}, role: :read, path: "", with_etls: false, schema: "bolt", prefix: :default, hostname: 'e334e499.databases.neo4j.io', basic_auth: [username: "neo4j", password: ""], port: 7687, pool_size: 50, ssl: true, max_overflow: 5, timeout: 15000, server_version: %{"connection_id" => "bolt-6752", "hints" => %{"connection.recv_timeout_seconds" => 60}, "server" => "Neo4j/4.4-aura"}], sock: {:sslsocket, {:gen_tcp, #Port<0.30>, :tls_connection, :undefined}, [#PID<0.836.0>, #PID<0.801.0>]}}}
```


```elixir
 @impl true
  def start(_type, _args) do
    children = [
      # Start the Ecto repository
      # Dhemi.Repo,
      {Bolt.Sips, Application.get_env(:bolt_sips, :read)},
      # Start the Telemetry supervisor
      # DhemiWeb.Telemetry,
      # Start the PubSub system
      # {Phoenix.PubSub, name: Dhemi.PubSub},
      # Start the Endpoint (http/https)
      DhemiWeb.Endpoint
      # Start a worker by calling: Dhemi.Worker.start_link(arg)
      # {Dhemi.Worker, arg}
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Dhemi.Supervisor, idle_interval: 5_000]
    Supervisor.start_link(children, opts)
  end
```


```elixir
config :bolt_sips, Bolt,
  hostname: 'secret.databases.neo4j.io',
  basic_auth: [username: "neo4j", password: "secret"],
  port: 7687,
  pool_size: 50, # Default: 15
  ssl: true, #  Default:false
  max_overflow: 5,
  timeout: 15_000  # milliseconds!

config :bolt_sips, :read,
  hostname: 'secret.databases.neo4j.io',
  basic_auth: [username: "neo4j", password: "secret"],
  port: 7687,
  pool_size: 50, # Default: 15
  ssl: true, #  Default:false
  max_overflow: 5,
  timeout: 15_000,  # milliseconds!
  role: :read
```

**Comment by florinpatrascu** [comment]
Hi there - as I was replying to your email, I tried to create a connection to the service you mentioned and it works as expected, with the current driver version. My connection config:

```elixir
config :bolt_sips, Bolt,
  url: "bolt://e<*****>.databases.neo4j.io",
  basic_auth: [username: "neo4j", password: "a--<*******>"],
  pool_size: 10,
  ssl: true,
  max_overflow: 2,
  queue_interval: 500,
  queue_target: 1500,
  prefix: :default
```

Please adapt the config above to your own connection details and try again. Notice please the use of `url`
