### ISSUE TITLE
Getting unpack error

### ISSUE THREAD

**Issue by nateless** [florinpatrascu/bolt_sips#9]
I'm getting:

```
    ** (EXIT) an exception was raised:
        ** (FunctionClauseError) no function clause matching in Boltex.Bolt.unpack/1
            (bolt_sips) lib/boltex/bolt.ex:234: Boltex.Bolt.unpack({:error, :timeout})
            (bolt_sips) lib/boltex/bolt.ex:198: Boltex.Bolt.receive_data/3
            (bolt_sips) lib/boltex/bolt.ex:154: Boltex.Bolt.run_statement/4
            (bolt_sips) lib/bolt_sips/connection.ex:52: Bolt.Sips.Connection.handle_call/3
            (stdlib) gen_server.erl:615: :gen_server.try_handle_call/4
            (stdlib) gen_server.erl:647: :gen_server.handle_msg/5
            (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

For this query: `USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM \"file:/import_1482495188_5.csv\" AS row MERGE (:A {aid: toInteger(row.aid), name: row.name})`
which can take up to 20 seconds to process.

**Comment by florinpatrascu** [comment]
yes, I didn't provisioned the driver for that particular error: `:timeout`, thank for reporting it. I'm gonna fix this while working on #8 - unrelated. Not being convinced the timeout is related to the driver though?!

**Comment by nateless** [comment]
Hey, I wonder whether it has been triggered by @recv_timeout    1_000 ? And if query took more than 1 second, will it be terminated or no?

**Comment by florinpatrascu** [comment]
Possibly. I'll refactor the code to use the configurable :timeout param, the one you can define in the config files. I overlooked that when I imported the code from Boltex.

**Comment by florinpatrascu** [comment]
please check the with_tls branch, the timeout will be the one you define in the config files or the default: 15 seconds. HTH

**Comment by florinpatrascu** [comment]
@nateless - do you also have the log for the error above? Just curious if it was properly logged. ty

**Comment by florinpatrascu** [comment]
new version: `0.1.4`, available at [Hex.pm](https://hex.pm/packages/bolt_sips/0.1.4)
