### ISSUE TITLE
Request: guidance on parameterized queries

### ISSUE THREAD

**Issue by taobojlen** [florinpatrascu/bolt_sips#90]
Cypher supports [parameterized queries](https://neo4j.com/docs/cypher-manual/current/syntax/parameters/) to help mitigate the risk of injection attacks.

It looks like `Bolt.Sips.query/2` only takes a connection and a string, and (as far as I can tell) none of the examples in this repo use parameterized queries. Does bolt_sips support these? If so, how do we use them without resorting to string building?

**Comment by florinpatrascu** [comment]
What about [query/4](https://hexdocs.pm/bolt_sips/Bolt.Sips.Query.html#query/4)? One of the tests we have, for brevity:

```elixir
  test "run simple statement with complex params", context do
    conn = context[:conn]

    row =
      Bolt.Sips.query!(conn, "RETURN {x} AS n", %{x: %{abc: ["d", "e", "f"]}})
      |> Response.first()

    assert row["n"]["abc"] == ["d", "e", "f"]
  end
```

**Comment by taobojlen** [comment]
Oh, my bad! I was searching for "parameter", so "params" didn't show up... Oops!

Thanks a lot for the fast reply :)

**Comment by florinpatrascu** [comment]
No worries :)

**Comment by dominique-vassard** [comment]
@tao-oat Keep in mind that due to deprecation Neo4j v4, it's better to use `$param` instead of `{param}`.
