### ISSUE TITLE
Outgoing SSL connection hangs, cannot be dropped and re-established

### ISSUE THREAD

**Issue by ekobi** [florinpatrascu/bolt_sips#95]
# Precheck

* For bugs, do a quick search and make sure the bug has not yet been reported. -- check
* Finally, be nice and have fun! -- check

## Environment

* Elixir version (elixir -v):

      Erlang/OTP 23 [erts-11.0.2] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [hipe] [dtrace]

      Elixir 1.10.4 (compiled with Erlang/OTP 23)
* Neo4j and version (Neo4j 3.5.3, etc.):

      Neo4j Community Edition 3.5.14

* Connection scheme (`bolt://`, `bolt+routing://` or `neo4j://`):

      bolt://

* Bolt.Sips version (mix deps):

        bolt_sips 2.0.8 (Hex package) (mix)
        locked at 2.0.8 (bolt_sips) 77a6b517

* Operating system:
  (Issue first observed on instance deployed on gigalixir; reproduced on macos system locally)

      kobi@blackbird api $ uname -a
      Darwin blackbird.local 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64

## Current behavior
My app loses, then is unable to re-establish, its SSL connection to my graphene database server instance. I first saw the failure from a Google Cloud-based Elixir hosting service (gigalixir), and again while running a local Elixir deployment on my workstation at around 5pm EST today. Typical error log message appended below.

One strong possibility is that the connection is getting dropped by AWS after being idle for 10 minutes. I sniffed for TCP keepalives, and although it's hard to make a generalized statement, the db_connection driver seems to send them out after the first 600s or so, which would be right at the threshold. **Q: is it possible to directly configure the `idle_timeout` via Bolt-Sips?** Any other thoughts on what's happening? Cheers,

## Error log / Stack Trace

          (bolt_sips 2.0.8) lib/bolt_sips/protocol.ex:85: Bolt.Sips.Protocol.disconnect/2

      ** (MatchError) no match of right hand side value: %Bolt.Sips.Internals.Error{code: nil, connection_id: nil, function: :goodbye, message: "goodbye: Unknown failure: \"Can't close port\"\n", type: :protocol_error}

      19:47:31.105 [error] GenServer #PID<0.467.0> terminating

          (db_connection 2.2.2) lib/db_connection/connection.ex:136: DBConnection.Connection.disconnect/2

          (connection 1.0.4) lib/connection.ex:767: Connection.disconnect/3

          (stdlib 3.13) proc_lib.erl:236: :proc_lib.wake_up/3

          (stdlib 3.13) gen_server.erl:680: :gen_server.try_dispatch/4

          (stdlib 3.13) gen_server.erl:756: :gen_server.handle_msg/6

      Last message: {:"$gen_cast", {:disconnect, #Reference<0.2335942036.437125121.151593>, %Bolt.Sips.Internals.Error{code: nil, connection_id: nil, function: :receive_data, message: "Port {:sslsocket, {:gen_tcp, #Port<0.11>, :tls_connection, :undefined}, [#PID<0.490.0>, #PID<0.480.0>]} is closed", type: :connection_error}, %Bolt.Sips.Protocol.ConnData{bolt_version: 3, configuration: [socket: :ssl, port: 24787, routing_context: %{}, schema: "bolt", hostname: "*************.graphenedb.com", pool_index: 1, name: {:via, Registry, {:bolt_sips_registry, "default_direct@***************.graphenedb.com:24787"}}, role: :direct, max_overflow: 0, timeout: 15000, with_etls: false, prefix: :default, url: "bolt://db-xyjg0kingtu1pztbekyz.graphenedb.com:24787", ssl: true, basic_auth: [username: '*********', password: "***********"], pool_size: 10, server_version: %{"connection_id" => "bolt-1006", "server" => "Neo4j/3.5.14"}], sock: {:sslsocket, {:gen_tcp, #Port<0.11>, :tls_connection, :undefined}, [#PID<0.490.0>, #PID<0.480.0>]}}}}
## Expected behavior

**Comment by florinpatrascu** [comment]
>  Q: is it possible to directly configure the idle_timeout via Bolt-Sips?

Yes. Any config parameters you add to the driver and they are also supported by the underlining library DBConnection, will be used to initialize the pool. For example:

```elixir
iex» {:ok, neo} = Sips.start_link(url: "bolt://neo4j:test@localhost", idle_interval: 2_000)
```

For brevity, when `:idle_interval` is set and if no requests are received for the idle interval specified, the pool will ping all stale connections which can then ping the database to keep the connection alive.

Please try and let us know if it works. It's been a while since I've worked with  this setting :)

HTH

**Comment by ekobi** [comment]
Thanks for the hint, Florin.

Unfortunately the effect of applying the idle_interval setting is not readily obvious to me (from staring at WireShark traces for far too long :). I don't actually see keepalives emanating from my end, even though the connections remain stable for longer than before. Very puzzling. I'll let you know if I figure this out. Cheers,
--
kobi
